### ISSUE TITLE
AttributeError: 'module' object has no attribute 'format_type' in 2.0.0

### ISSUE THREAD

**Issue by lucacorti** [django-json-api/django-rest-framework-json-api#236]
After upgrading from 2.0.0b2 to 2.0.0 I get:

```
Traceback (most recent call last):
  File "django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "rest_framework/response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "rest_framework/renderers.py", line 712, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "rest_framework/renderers.py", line 738, in get_context
    data, accepted_media_type, renderer_context
  File "rest_framework/renderers.py", line 637, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "rest_framework/renderers.py", line 399, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "rest_framework_json_api/renderers.py", line 451, in render
    json_resource_obj = self.build_json_resource_obj(fields, resource, resource_instance, resource_name)
  File "rest_framework_json_api/renderers.py", line 368, in build_json_resource_obj
    relationships = JSONRenderer.extract_relationships(fields, resource, resource_instance)
  File "rest_framework_json_api/renderers.py", line 214, in extract_relationships
    relation_type = utils.format_type(relation_model.__name__)
AttributeError: 'module' object has no attribute 'format_type'
```

There is no `utils.fomat_type()` indeed.

**Comment by jerel** [comment]
Thanks for reporting, fixed by 5cf3526b21efbf997069bbce4c2583941a26fa4f

**Comment by patroqueeet** [comment]
when is it due for pypi? looks like its breaking my project and a stable release would be really great!

**Comment by jerel** [comment]
v2.0.1 has been on pypi for a couple weeks. `pip install djangorestframework-jsonapi==v2.0.1` should force pip to download it

**Comment by patroqueeet** [comment]
you're right. that's why I deleted my comment again. just pypi index search did by any reason not show it. the install worked. thx!
