### ISSUE TITLE
Django 1.11 w/ MTM - TypeError: add() got an unexpected keyword argument 'bulk'

### ISSUE THREAD

**Issue by firstgeneration** [django-json-api/django-rest-framework-json-api#342]
Hi, when working with Django 1.11 and a many-to-many relationship:

`PATCH   http://api/primary_resource/:id/relationships/related_resource`

Raises a: `TypeError: add() got an unexpected keyword argument 'bulk'`

I'm new to python/django, but it looks like two years ago this was added to handle an error caused by Django 1.9.
https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/views.py#L138

I tested removing the bulk kwarg and it worked fine. And POST works fine as is (since provides no bulk kwarg), which is what I'm using, however, wanted to raise the PATCH issue. Thank you!
